spring:
  jackson:
    default-property-inclusion: non_null

logging:
  level:
    root: warn
    org.example: debug
  pattern:
    console: '%-5level %C.%M[%line] - %msg%n'

my:
  secretkey: R28K42ZEJ8LWRHU5